version: "3.2"
services:

  mssql:
    container_name: container_mssql2017
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      SA_PASSWORD: "SApassSQLyear2017"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - "/data/mssql2017:/var/opt/mssql/data"
