version: '3'
services:
  redis:
    container_name: redis-server
    restart: always
    image: redis
    command: redis-server --requirepass secret
    networks:
      - default
    ports:
      - 6379:6379
